version: '3'

services:
    redis:
        image: redis:6.2.2-alpine
        restart: on-failure
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - redis-data:/data

    rabbit:
        image: rabbitmq:3-management
        restart: on-failure
        hostname: rabbit
        ports:
            - '15672:15672'

    services:
        build:
            context: services
        restart: on-failure
        depends_on:
            - rabbit
        environment:
            REDIS_HOST: 'redis'
            REDIS_PORT: '6379'
            RABBIT_PASSWORD: 'guest'
            RABBIT_USER: 'guest'
            RABBIT_HOST: 'rabbit'
            RABBIT_PORT: '5672'

    client:
        build:
            context: client
        restart: on-failure
        depends_on:
            - rabbit
            - redis
            - services
        ports:
            - '5000:5000'
        environment:
            REDIS_HOST: 'redis'
            REDIS_PORT: '6379'
            RABBIT_PASSWORD: 'guest'
            RABBIT_USER: 'guest'
            RABBIT_HOST: 'rabbit'
            RABBIT_PORT: '5672'

volumes:
    redis-data:
